spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/Jpa?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

